name: Tests

on: [push, pull_request]

env:
  DUSK_DRIVER_MANAGEMENT: false

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0]
        laravel: [8.*, 7.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      # -----------------------------
      # Install Chrome + Chromedriver
      # -----------------------------
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Chromedriver
        uses: browser-actions/setup-chromedriver@v1

      - name: Start Chromedriver
        run: |
          chromedriver --port=9515 &
          sleep 2

      # -----------------------------
      # Composer install
      # -----------------------------
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench-dusk:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      # -----------------------------
      # Run Dusk tests
      # -----------------------------
      - name: Execute tests
        run: php artisan dusk --without-test-updater --debug
